-- Design notes:
-- Every entity table must have a technical primary key ('id'), generated by own sequence
CREATE SEQUENCE product_sequence START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE category_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE category
(
    id          BIGINT DEFAULT nextval('category_sequence') NOT NULL PRIMARY KEY,
    name        VARCHAR(255)                                NOT NULL UNIQUE,
    description VARCHAR
);

CREATE TABLE product
(
    id          BIGINT DEFAULT nextval('product_sequence') NOT NULL PRIMARY KEY,
    name        VARCHAR(255)                               NOT NULL,
    image_url   VARCHAR(512),
    description VARCHAR(2048),
    price       FLOAT                                      NOT NULL CHECK (price > 0),
    category_id BIGINT                                     NOT NULL,
    FOREIGN KEY (category_id) REFERENCES category (id)  ON DELETE CASCADE
);

